Repository YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-frontend, pull requests merged in 2020-09, with the labels that each got.

#19 Added typescript features to react project
  package.json
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: enhancement

#21 Feature/login page
  public/favicon.ico
  public/favicon_react.ico
  public/index.html
  src/components/App/App.css
  src/components/App/App.test.tsx
  src/components/App/App.tsx
  src/components/LogIn/Button.css
  src/components/LogIn/Button.tsx
  src/components/LogIn/Image.tsx
  src/components/LogIn/LogIn.css
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/LoginBox.css
  src/components/LogIn/LoginBox.tsx
  src/components/LogIn/TextField.css
  src/components/LogIn/TextField.tsx
  src/images/loginbgs/bg1.jpg
  src/images/loginbgs/bg2.jpg
  src/images/loginbgs/bg3.jpg
  src/images/loginbgs/bg4.jpg
  src/images/loginbgs/bg5.jpg
  src/images/swarmLogoIcon.png
  src/index.css
  src/index.tsx
  src/serviceWorker.js
Labels: enhancement

#24 feature/routing
  src/App.tsx
  src/components/LogIn/LoginBox.tsx
  src/index.tsx
Labels: enhancement

#25 Feature/cleanup login
  src/App.tsx
  src/components/Error/Error.tsx
  src/components/LogIn/Button.css
  src/components/LogIn/Button.tsx
  src/components/LogIn/Image.tsx
  src/components/LogIn/LogIn.css
  src/components/LogIn/LogIn.tsx
  src/components/LogIn/LoginBox.css
  src/components/LogIn/LoginBox.tsx
  src/components/LogIn/TextField.css
  src/components/LogIn/TextField.tsx
  src/utils/Button.tsx
  src/utils/Image.tsx
  src/utils/TextField.tsx
Labels: enhancement

#27 Added the start to the homepage
  src/App.tsx
  src/components/Home/HomePage.css
  src/components/Home/HomePage.tsx
  src/components/LogIn/LogIn.tsx
  src/index.tsx
  src/styles/backgroundImageStyling.ts
  src/styles/styles.css
  src/utils/MainNavbar.tsx
Labels: good first issue

#37 Changed list item names for devcard and sponsorcard
  src/components/PersonalPage/DevCard/DevCard.css
  src/components/PersonalPage/DevCard/DevCard.tsx
  src/components/PersonalPage/PersonalPage.tsx
  src/components/PersonalPage/SponsorCard/SponsorCard.css
  src/components/PersonalPage/SponsorCard/SponsorCard.tsx
Labels: bug

#38 hotFix/images
  .gitattributes
  public/favicon.ico
  src/images/swarmLogoIcon.png
Labels: bug

#46 bugFix/backgrounds
  src/images/loginbgs/bg1.jpg
  src/images/loginbgs/bg2.jpg
  src/images/loginbgs/bg3.jpg
  src/images/loginbgs/bg4.jpg
  src/images/loginbgs/bg5.jpg
Labels: bug

#48 Fixed navbar spacing
  src/styles/styles.css
  src/utils/MainNavbar.tsx
Labels: enhancement

#47 Feature/fontfix
  src/components/LogIn/LogIn.css
  src/components/SignUp/SignUp.css
  src/index.tsx
  src/styles/styles.css
Labels: enhancement
