Repository YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-frontend, pull requests merged in 2020-11, with the labels that each got.

#61 bugFix/contribCount
  src/components/Wiki/Landing/Landing.tsx
Labels: bug

#66 [DONE] Fixed button redirects for the navbar
  src/utils/MainNavbar.tsx
Labels: bug, enhancement

#63 [DONE] Feature/user cookies
  src/components/Home/HomePage.tsx
  src/components/LogIn/LogIn.tsx
  src/components/PersonalPage/SponsorCard/SponsorCard.tsx
  src/components/Wiki/Wiki.tsx
  src/utils/verifiyUserIsLoggedIn/verifyLoggedIn.ts
Labels: enhancement

#68 bugFix/favicon
  .gitattributes
  public/favicon.ico
Labels: bug

#69 feature/wikiCookiesImpl
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/Entry/deleteEntry.ts
  src/components/Wiki/Entry/postComment.ts
  src/components/Wiki/EntryEditForm/EntryEditForm.tsx
  src/components/Wiki/EntryEditForm/UpdateEntry.ts
  src/components/Wiki/EntryEditForm/postNewHeading.ts
  src/components/Wiki/EntryMenu/EntryMenu.tsx
  src/components/Wiki/EntryMenu/postEntry.ts
  src/components/Wiki/Landing/Landing.tsx
  src/components/Wiki/Wiki.tsx
  src/components/Wiki/WikiNotFound/WikiNotFound.tsx
  src/components/Wiki/postWiki.ts
  src/utils/MainNavbar.tsx
  src/utils/getInterfaces/userData.ts
Labels: enhancement

#78 feature/editTabHide
  src/components/Wiki/Entry/Entry.tsx
Labels: enhancement

#77 feature/deleteComments
  src/components/Wiki/Entry/Entry.css
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/Entry/deleteComment.ts
Labels: enhancement

#79 feature/deleteHeadings
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/EntryEditForm/EntryEditForm.tsx
  src/components/Wiki/EntryEditForm/deleteHeading.ts
Labels: enhancement

#80 feature/lastUpdatedDate
  src/components/Wiki/EntryMenu/EntryMenu.tsx
Labels: enhancement

#83 Stored the cookies for the background image
  src/components/LogIn/LogIn.tsx
  src/styles/backgroundImageStyling.ts
Labels: enhancement

#81 feature/deleteWikis
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/EntryEditForm/EntryEditForm.tsx
  src/components/Wiki/EntryEditForm/postHeading.ts
  src/components/Wiki/Wiki.tsx
  src/components/Wiki/deleteWiki.ts
Labels: enhancement

#85 bugFix/deleteHeadings
  src/components/Wiki/EntryEditForm/deleteHeading.ts
Labels: bug

#84 feature/updateWikis
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/EntryEditForm/EntryEditForm.tsx
  src/components/Wiki/EntryEditForm/updateEntry.ts
  src/components/Wiki/Wiki.tsx
  src/components/Wiki/deleteWiki.ts
  src/components/Wiki/updateWiki.ts
Labels: enhancement
