Repository YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-frontend, pull requests merged in 2021-02, with the labels that each got.

#95 Changed to post request
  src/components/LogIn/LoginApi.ts
Labels: bug, enhancement

#93 refactor/wiki
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/Entry/apiCalls.ts
  src/components/Wiki/Entry/deleteComment.ts
  src/components/Wiki/Entry/postComment.ts
  src/components/Wiki/EntryMenu/EntryMenu.tsx
  src/components/Wiki/EntryMenu/apiCalls.ts
  src/components/Wiki/EntryMenu/postEntry.ts
  src/components/Wiki/Landing/Landing.tsx
  src/components/Wiki/Landing/apiCalls.ts
  src/components/Wiki/Wiki.tsx
  src/components/Wiki/apiCalls.ts
Labels: refactor

#96 Refactor/api urls
  src/utils/DetermineUrl.ts
Labels: refactor

#98 bugFix/loginCSS
  .gitignore
  src/components/LogIn/LogIn.css
Labels: bug

#103 feature/visualizationLinks
  src/components/Home/HomePage.tsx
  src/utils/MainNavbar.tsx
Labels: enhancement, refactor

#105 bugFix/homePage
  src/components/Home/HomePage.css
  src/styles/styles.css
Labels: bug

#102 refactor/wikiReloading
  .gitignore
  src/components/Dog/Dog.tsx
  src/components/Wiki/Entry/Entry.css
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/Entry/apiCalls.ts
  src/components/Wiki/Entry/deleteEntry.ts
  src/components/Wiki/EntryEditForm/EntryEditForm.tsx
  src/components/Wiki/EntryEditForm/apiCalls.ts
  src/components/Wiki/EntryEditForm/deleteHeading.ts
  src/components/Wiki/EntryEditForm/postHeading.ts
  src/components/Wiki/EntryEditForm/updateEntry.ts
  src/components/Wiki/EntryEditForm/updateHeadings.ts
  src/components/Wiki/EntryMenu/EntryMenu.tsx
  src/components/Wiki/EntryMenu/apiCalls.ts
  src/components/Wiki/Wiki.tsx
  src/components/Wiki/deleteWiki.ts
  src/components/Wiki/postWiki.ts
  src/components/Wiki/updateWiki.ts
  src/utils/MainNavbar.tsx
Labels: refactor

#111 Change http to https
  src/utils/DetermineUrl.ts
Labels: bug

#109 bugFix/registration
  src/components/SignUp/SignUp.css
Labels: bug

#107 feature/changeViewing
  src/components/Wiki/Entry/Entry.css
  src/components/Wiki/Entry/Entry.tsx
  src/components/Wiki/Entry/apiCalls.ts
  src/components/Wiki/EntryEditForm/EntryEditForm.tsx
  src/components/Wiki/EntryEditForm/apiCalls.ts
  src/utils/getInterfaces/changeData.ts
Labels: enhancement
